export default [
  { q: 'Besides making food salty, salt…', choices: ['Adds sweetness directly', 'Suppresses bitterness and amplifies aroma', 'Cools food down', 'Replaces acid'], answer: 1 },
  { q: 'When should a whole chicken ideally be salted?', choices: ['Right after cooking', 'At least 45 minutes before, ideally the morning of', 'Only at the table', 'Never'], answer: 1 },
  { q: 'A teaspoon of fine table salt compared with a teaspoon of flaky salt is…', choices: ['Less salty', 'About the same', 'Roughly twice as salty', 'Ten times as salty'], answer: 2 },
  { q: 'The Maillard reaction needs…', choices: ['Lots of water', 'Heat and a dry surface', 'Sugar only', 'A lid'], answer: 1 },
  { q: 'Mushrooms crowded into one pan turn grey and rubbery because…', choices: ['They are old', 'They release water and steam instead of browning', 'The pan is too hot', 'They need salt'], answer: 1 },
  { q: 'For a high-heat sear you should use…', choices: ['Extra-virgin olive oil', 'Butter', 'A neutral oil like canola or grapeseed', 'Water'], answer: 2 },
  { q: 'A dish tastes flat and salt does not fix it. It most likely needs…', choices: ['More sugar', 'Acid, like lemon or vinegar', 'More cooking time', 'Flour'], answer: 1 },
  { q: 'A basic vinaigrette uses oil to vinegar in about…', choices: ['1:1', '3:1', '1:3', '10:1'], answer: 1 },
  { q: '"Mise en place" means…', choices: ['A French cheese', 'Cutting and measuring everything before heat goes on', 'A type of knife', 'Serving on plates'], answer: 1 },
  { q: 'A sharp knife is safer than a dull one because…', choices: ['It is heavier', 'It does not slip', 'It cuts more slowly', 'It is easier to see'], answer: 1 },
  { q: 'Why cut stew carrots to the same size?', choices: ['For looks only', 'Same size means same cooking time', 'To save knife wear', 'Because recipes say so'], answer: 1 },
  { q: 'The "fond" is…', choices: ['A French sauce', 'The browned residue stuck to the pan after searing', 'A type of stock cube', 'The bottom shelf of the fridge'], answer: 1 },
  { q: 'Deglazing means…', choices: ['Removing the glaze from a ham', 'Adding liquid to a hot pan and scraping up the browned bits', 'Cooling a pan in water', 'Adding sugar'], answer: 1 },
  { q: 'The easiest way to thicken a pan sauce is to…', choices: ['Add flour directly', 'Reduce it by simmering', 'Add ice', 'Blend it'], answer: 1 },
  { q: 'Egg whites set at roughly…', choices: ['40°C', '63°C', '90°C', '120°C'], answer: 1 },
  { q: 'Good scrambled eggs are…', choices: ['Cooked on high heat without stirring', 'Cooked low and slow with constant stirring and pulled while slightly wet', 'Boiled first', 'Left in the pan to finish'], answer: 1 },
  { q: 'Grey, chalky boiled-egg yolks mean…', choices: ['The eggs were too fresh', 'They were overcooked', 'Too much salt in the water', 'The eggs were cold'], answer: 1 },
  { q: 'A jammy boiled egg takes about…', choices: ['3 minutes', '6 minutes', '12 minutes', '20 minutes'], answer: 1 },
  { q: 'Frozen vegetables are…', choices: ['Always worse than fresh', 'Often fresher than week-old "fresh" produce, since they are picked ripe', 'Unsafe', 'Only for soups'], answer: 1 },
  { q: 'With chickpeas, onion, garlic, tomatoes, cumin, and lemon you can make…', choices: ['Nothing useful', 'A simple stew: soften onion and garlic with cumin, add tomatoes and chickpeas, simmer, finish with lemon', 'Only hummus', 'Dessert'], answer: 1 },
];
