export default [
  { q: 'Why do most major old cities sit on water?', choices: ['For the view', 'Water meant drinking, transport, defense, and trade before roads and rail', 'Because of religious rules', 'Because land was cheaper there'], answer: 1 },
  { q: 'Marseille was founded around 600 BC by…', choices: ['Romans', 'Greeks', 'Phoenicians', 'Vikings'], answer: 1 },
  { q: 'Chicago grew into a giant city mainly because…', choices: ['It has a warm climate', 'It sits where the Great Lakes route meets the Mississippi system and railroads converged', 'Gold was found there', 'It was the first US capital'], answer: 1 },
  { q: 'Roughly what share of the world\'s oil passes through the Strait of Hormuz?', choices: ['About 2%', 'About a fifth', 'About half', 'Almost all'], answer: 1 },
  { q: 'Which waterway links Europe and Asia without going around Africa?', choices: ['The Panama Canal', 'The Suez Canal', 'The Bosporus', 'The Strait of Malacca'], answer: 1 },
  { q: 'When ships avoided the Red Sea and sailed around Africa, the Asia–Europe trip lengthened by about…', choices: ['1–2 days', '10–14 days', '2 months', 'It got shorter'], answer: 1 },
  { q: 'Which river is at the center of a dispute between Ethiopia and Egypt?', choices: ['The Congo', 'The Niger', 'The Nile', 'The Zambezi'], answer: 2 },
  { q: 'Why would a country spend heavily to claim an uninhabited reef?', choices: ['For tourism', 'Sovereignty can extend claims to fishing, oil, gas, and shipping control in surrounding waters', 'To build a lighthouse', 'For scientific prestige only'], answer: 1 },
  { q: 'Many straight-line borders in Africa and the Middle East date from…', choices: ['Ancient tribal agreements', 'European colonial administrators', 'The United Nations in 1990', 'Natural rivers'], answer: 1 },
  { q: 'Paris has mild winters despite its latitude mainly because of…', choices: ['The Alps', 'The Gulf Stream and Atlantic influence', 'City heating', 'Its low altitude'], answer: 1 },
  { q: 'The east side of the Sierra Nevada is a desert because…', choices: ['It is farther from the equator', 'Moist Pacific air drops its rain on the western slopes (rain shadow)', 'It is below sea level', 'Of volcanic soil'], answer: 1 },
  { q: 'Coffee typically grows in…', choices: ['Temperate lowlands', 'Tropical highlands', 'Arctic tundra', 'Mediterranean coasts'], answer: 1 },
  { q: 'Which two regional powers are usually described as rivals in the Middle East?', choices: ['Egypt and Turkey', 'Saudi Arabia and Iran', 'Jordan and Lebanon', 'Qatar and Oman'], answer: 1 },
  { q: 'Which country controls the Suez Canal?', choices: ['Saudi Arabia', 'Israel', 'Egypt', 'Turkey'], answer: 2 },
  { q: 'Yemen\'s Houthi movement is backed by…', choices: ['Saudi Arabia', 'Iran', 'Egypt', 'Turkey'], answer: 1 },
  { q: 'Which country is in Schengen and NATO but not in the EU?', choices: ['Ireland', 'Norway', 'Poland', 'Sweden'], answer: 1 },
  { q: 'When the ECB raises rates, mortgages are affected in…', choices: ['Warsaw', 'Copenhagen', 'Marseille', 'London'], answer: 2 },
  { q: 'Which US region has grown fastest in recent years?', choices: ['The Northeast', 'The Midwest', 'The South', 'Alaska'], answer: 2 },
  { q: 'US politics maps most closely onto…', choices: ['Coast vs. interior', 'Population density: cities lean Democratic, rural areas Republican, suburbs decide', 'North vs. South only', 'Altitude'], answer: 1 },
  { q: 'Why do a few swing states dominate presidential campaigns?', choices: ['They have the most people', 'The Electoral College is winner-take-all in almost every state, so only uncertain states can flip the result', 'They vote first', 'Federal law requires it'], answer: 1 },
];
