export default [
  { q: 'A company is split into 500,000 shares and you own 5,000. What fraction of the company do you own?', choices: ['0.1%', '1%', '10%', '0.01%'], answer: 1 },
  { q: 'Who sets the price of a share?', choices: ['The company\'s board', 'The exchange', 'The last buyer and seller who agreed on a trade', 'The government'], answer: 2 },
  { q: 'Which of these does owning one share NOT give you?', choices: ['A claim on part of the profits', 'A vote at the annual meeting', 'The right to use company property', 'A share of dividends if paid'], answer: 2 },
  { q: 'What are the regular trading hours of the New York Stock Exchange?', choices: ['8:00 AM–5:00 PM Eastern', '9:30 AM–4:00 PM Eastern', '9:00 AM–4:30 PM Eastern', '24 hours'], answer: 1 },
  { q: 'A market order to buy…', choices: ['executes only at or below your chosen price', 'executes as fast as possible at the current price', 'executes at yesterday\'s close', 'is cancelled at the end of the day'], answer: 1 },
  { q: 'The quote shows bid $50.00 / ask $50.10. A market buy costs you about…', choices: ['$50.00', '$50.05', '$50.10', 'Whichever is lower'], answer: 2 },
  { q: 'When someone says "the market was up 1% today", they most likely mean…', choices: ['The Dow Jones', 'The S&P 500', 'The Nasdaq Composite', 'The CAC 40'], answer: 1 },
  { q: 'How many companies does the Dow Jones Industrial Average follow?', choices: ['30', '100', '500', 'About 3,000'], answer: 0 },
  { q: 'Most large indices are weighted by…', choices: ['Alphabetical order', 'Share price', 'Company size (market value)', 'Number of employees'], answer: 2 },
  { q: 'An index closes at 5,200, down 78 points. The percentage move is about…', choices: ['-0.78%', '-1.5%', '-7.8%', '-15%'], answer: 1 },
  { q: 'A retailer grows sales 12% but analysts expected 15%. The stock most likely…', choices: ['Rises, because sales grew', 'Falls, because results missed expectations', 'Does not move', 'Is suspended from trading'], answer: 1 },
  { q: 'Prices react most strongly to…', choices: ['Any news', 'Surprises relative to expectations', 'Company press releases', 'Weekend headlines'], answer: 1 },
  { q: 'When safe government bonds start paying more interest, stocks tend to…', choices: ['Fall, because they look less attractive by comparison', 'Rise, because the economy is strong', 'Stay unchanged', 'Stop paying dividends'], answer: 0 },
  { q: 'Why have stocks returned more than savings accounts over long periods?', choices: ['Because they are safer', 'As compensation for bearing the risk of large losses', 'Because banks pay no interest', 'Because of inflation only'], answer: 1 },
  { q: 'Money you need in nine months for a deposit belongs…', choices: ['In a broad stock fund', 'In a savings account or similar', 'In a single stock', 'In cryptocurrency'], answer: 1 },
  { q: 'A bear market is a fall of at least…', choices: ['5%', '10%', '20%', '50%'], answer: 2 },
  { q: 'An index peaks at 6,000 and drops to 4,900. That is…', choices: ['A correction', 'A bear market', 'A crash by definition', 'Neither, it is within normal daily noise'], answer: 0 },
  { q: 'Roughly how often has the S&P 500 had a 10% drop historically?', choices: ['Once a decade', 'Every year or two', 'Every month', 'Never since 1950'], answer: 1 },
  { q: 'A stock trades at $50, pays $2 a year in dividends, and earns $4 per share. Its P/E is…', choices: ['4', '12.5', '25', '50'], answer: 1 },
  { q: 'The dividend yield of that same stock is…', choices: ['2%', '4%', '8%', '25%'], answer: 1 },
];
