export default [
  { q: 'An index fund…', choices: ['Pays managers to pick winners', 'Holds everything in an index in the same proportions', 'Only buys bonds', 'Trades once a year'], answer: 1 },
  { q: 'Over long periods, most active funds have…', choices: ['Beaten their index after fees', 'Failed to beat their index after fees', 'Matched it exactly', 'Gone bankrupt'], answer: 1 },
  { q: 'An S&P 500 fund charges 0.03% a year. On $20,000, the yearly fee is…', choices: ['$0.60', '$6', '$60', '$600'], answer: 1 },
  { q: 'Which type of company most often pays dividends?', choices: ['Young, fast-growing companies', 'Mature companies with steady profits', 'Companies with no profit', 'Companies about to go public'], answer: 1 },
  { q: 'A very high dividend yield (8%+) is often…', choices: ['A sign of safety', 'A warning that the market doubts the dividend will last', 'Required by law', 'Only found in banks'], answer: 1 },
  { q: 'After a company buys back 10% of its shares, each remaining share…', choices: ['Owns a smaller slice of the company', 'Owns a larger slice of the company', 'Is worth exactly the same', 'Loses its vote'], answer: 1 },
  { q: 'A P/E of 20 means…', choices: ['The stock pays 20% a year', 'You pay $20 for every $1 of yearly profit', 'The company has 20 years of debt', 'Profit grew 20%'], answer: 1 },
  { q: 'A stock at $150 earned $5 per share last year. Its trailing P/E is…', choices: ['15', '20', '30', '75'], answer: 2 },
  { q: 'When interest rates rise, prices of existing bonds…', choices: ['Rise', 'Fall', 'Do not change', 'Become zero'], answer: 1 },
  { q: 'Which bond is considered about the safest asset in the world?', choices: ['A junk bond', 'A US Treasury', 'A corporate bond', 'A municipal bond'], answer: 1 },
  { q: 'If you hold a bond to maturity, a drop in its market price…', choices: ['Reduces your coupon payments', 'Only matters if you sell', 'Forces the issuer to pay more', 'Cancels the bond'], answer: 1 },
  { q: 'The decision that matters most for long-run results is…', choices: ['Which specific fund you pick', 'The mix between stocks, bonds, and cash (asset allocation)', 'Which broker you use', 'The day of the week you buy'], answer: 1 },
  { q: 'Rebalancing means…', choices: ['Selling everything in a crash', 'Buying more of whatever rose most', 'Selling what has grown and buying what has lagged to return to your target mix', 'Changing brokers'], answer: 2 },
  { q: 'Ten stocks that are all US banks are…', choices: ['Fully diversified', 'Not really diversified, because they share the same risks', 'Safer than an index fund', 'Illegal to hold together'], answer: 1 },
  { q: '"Dow plunges 600 points" when the Dow is at 40,000 is a move of about…', choices: ['0.15%', '1.5%', '6%', '15%'], answer: 1 },
  { q: 'When a company "loses $100 billion in value in one day"…', choices: ['$100 billion in cash left investors\' accounts', 'The market price of its shares fell; losses are only realized when holders sell', 'The company went bankrupt', 'Its employees were paid less'], answer: 1 },
  { q: 'Missing the ten best days over a couple of decades has historically…', choices: ['Made little difference', 'Roughly halved returns', 'Doubled returns', 'Eliminated all risk'], answer: 1 },
  { q: 'Dollar-cost averaging means…', choices: ['Buying only when prices are low', 'Investing the same amount at regular intervals regardless of price', 'Converting dollars to euros', 'Buying one share a day'], answer: 1 },
  { q: 'A colleague says a stock "can only go up" because a launch is next month. The flaw is…', choices: ['Launches always fail', 'Public knowledge is already priced in; the stock moves on surprises', 'Stocks cannot rise on news', 'Launches are illegal to trade on'], answer: 1 },
  { q: 'In the US, which account types offer tax advantages for long-term investing?', choices: ['Checking accounts', '401(k) and IRA', 'Credit cards', 'Brokerage margin accounts'], answer: 1 },
];
