export default [
  { q: 'Which average is dragged around by extreme values?', choices: ['The median', 'The mean', 'The mode', 'None of them'], answer: 1 },
  { q: 'When mean and median differ a lot, the data is…', choices: ['Normal', 'Skewed, and the median is usually the honest "typical" value', 'Wrong', 'Too small'], answer: 1 },
  { q: 'A college reports average starting salary $72,000 and median $48,000. This means…', choices: ['Most graduates earn about $72,000', 'A few very high earners pull the mean up; most earn closer to $48,000', 'The data is fake', 'Half earn over $72,000'], answer: 1 },
  { q: 'A rate goes from 4% to 6%. That is…', choices: ['2 percentage points and 50% relative', '2% relative', '6 percentage points', '50 percentage points'], answer: 0 },
  { q: '"Doubles the risk" of something affecting 1 in 100,000 means…', choices: ['Half of people are affected', '2 in 100,000', '1 in 50', 'The risk is now certain'], answer: 1 },
  { q: 'Rates on tiny groups (e.g., 3 of 5 students) are…', choices: ['Very reliable', 'Prone to wild swings and privacy problems; show the counts', 'Illegal', 'Always rounded up'], answer: 1 },
  { q: 'Ice-cream sales and drownings both rise in summer. This is an example of…', choices: ['Causation', 'A third factor (heat) driving both', 'Random error', 'Reverse causation'], answer: 1 },
  { q: 'The strongest evidence for causation comes from…', choices: ['A large survey', 'A randomized experiment', 'An expert opinion', 'A chart'], answer: 1 },
  { q: 'Students who opt into a seminar are retained at 90% vs 78%. The main reason to doubt the seminar caused it is…', choices: ['The numbers are too close', 'Self-selection: those who opt in likely differ to begin with', 'Retention cannot be measured', 'The seminar is too short'], answer: 1 },
  { q: 'The margin of error (±3%) accounts for…', choices: ['Bias in who was asked', 'Only the randomness of sampling, assuming a representative sample', 'Question wording', 'Everything'], answer: 1 },
  { q: 'Which is more trustworthy for the whole population?', choices: ['50,000 self-selected website volunteers', '400 randomly selected registered voters', 'Whichever is larger', 'Neither'], answer: 1 },
  { q: 'A course evaluation with 12 of 40 responses, all glowing, tells the department…', choices: ['The course went well', 'Little, because the 28 non-respondents may differ systematically', 'The instructor should be promoted', 'The survey was too long'], answer: 1 },
  { q: 'A bar chart whose vertical axis starts at 90 instead of 0…', choices: ['Is more accurate', 'Exaggerates small differences', 'Is required by convention', 'Hides differences'], answer: 1 },
  { q: 'Before agreeing a stock is "soaring" from a three-month chart, check…', choices: ['The colors used', 'Axis start and scale, the time window, and how peers or the market did', 'The font', 'Only the last data point'], answer: 1 },
  { q: 'The best- and worst-performing schools in a state are usually small ones because…', choices: ['Small schools are better and worse', 'Small samples swing more by chance', 'They are underfunded', 'Rankings favor them'], answer: 1 },
  { q: 'Regression to the mean means…', choices: ['Things always get worse', 'An extreme result is usually followed by a more ordinary one, with no cause needed', 'Averages decline over time', 'Data reverts to zero'], answer: 1 },
  { q: 'A team improves after a terrible season and a new coach. A reason other than the coach is…', choices: ['Regression to the mean', 'Longer pools', 'New uniforms', 'The calendar'], answer: 0 },
  { q: 'A program with 8 students goes from 100% to 50% graduation. The honest reporting is…', choices: ['A 50-point collapse', 'The counts (8 of 8, then 4 of 8) and a multi-year average', 'Nothing', 'Only the second year'], answer: 1 },
  { q: 'Which is NOT one of the five integrity checks?', choices: ['Totals match the source', 'No unexpected duplicates', 'The chart uses brand colors', 'Categories sum to the total'], answer: 2 },
  { q: 'Most disagreements between two reports come from…', choices: ['Arithmetic errors', 'Different definitions or extract dates', 'Different fonts', 'Software bugs'], answer: 1 },
];
