export default [
  { q: 'In machine learning, the rules a model follows are…', choices: ['Written by a programmer', 'Learned from examples by adjusting internal numbers', 'Copied from a textbook', 'Set by the user each time'], answer: 1 },
  { q: 'Everything a model does is fundamentally…', choices: ['Understanding', 'Prediction', 'Memorizing', 'Reasoning like a human'], answer: 1 },
  { q: 'A hiring model trained on ten years of past decisions risks…', choices: ['Being too slow', 'Reproducing past biases at scale', 'Hiring nobody', 'Costing too much electricity'], answer: 1 },
  { q: 'In a neural network, "weights" are…', choices: ['The size of the training data', 'Adjustable numbers that are tuned during training', 'The number of layers', 'The electricity cost'], answer: 1 },
  { q: '"Deep" in deep learning refers to…', choices: ['Profound insights', 'Many layers', 'Underwater data centers', 'Long training times'], answer: 1 },
  { q: 'Why is it hard to explain a deep network\'s specific decision?', choices: ['The code is secret', 'The decision is the combined effect of millions of weights with no single readable rule', 'Engineers are not allowed to look', 'It changes every second'], answer: 1 },
  { q: 'A large language model is trained mainly to…', choices: ['Look up facts in a database', 'Predict the next word given the words so far', 'Translate between languages only', 'Browse the internet'], answer: 1 },
  { q: 'Why can the same question give different answers from the same model?', choices: ['The model is broken', 'Generation samples from probabilities rather than always taking the top word', 'The internet changed', 'It depends on the time of day'], answer: 1 },
  { q: 'A "hallucination" is…', choices: ['A fluent, confident statement that is false', 'A model refusing to answer', 'A slow response', 'An image the model generates'], answer: 0 },
  { q: 'Models are least reliable on…', choices: ['Widely documented general concepts', 'Specific numbers, names, citations, and recent events', 'Grammar', 'Common definitions'], answer: 1 },
  { q: 'Which request is safer to trust without checking?', choices: ['"What was our retention rate in 2023?"', '"Explain what a retention rate is"', '"Cite three studies on retention"', '"What did the dean say yesterday?"'], answer: 1 },
  { q: 'Which analytics task suits an AI assistant best?', choices: ['Deciding which of two conflicting data sources is authoritative', 'Drafting a DAX measure from a plain-English description', 'Taking responsibility for a state report', 'Knowing that program codes changed in 2022'], answer: 1 },
  { q: 'An AI "agent" is…', choices: ['A human employee', 'A model in a loop with tools that can act, look at results, and decide the next step', 'A faster model', 'A model with feelings'], answer: 1 },
  { q: 'Prompt injection is…', choices: ['A vaccine for computers', 'Text in content that a model may mistake for instructions', 'A way to speed up training', 'A type of chip'], answer: 1 },
  { q: 'An agent that can read AND send emails is riskier than a read-only one because…', choices: ['It uses more memory', 'Content in incoming mail could manipulate it into sending messages, which is hard to undo', 'Reading is illegal', 'Sending costs money'], answer: 1 },
  { q: 'The two main cost phases of a large model are…', choices: ['Design and marketing', 'Training and inference', 'Testing and shipping', 'Coding and debugging'], answer: 1 },
  { q: 'Which company\'s chips dominate AI training?', choices: ['Intel', 'Nvidia', 'IBM', 'Sony'], answer: 1 },
  { q: 'Why can one chip company\'s results move the whole S&P 500?', choices: ['Because indices are size-weighted and it is a very large share of the index', 'Because it is the only company in the index', 'Because of a law', 'Because chips are used in every product'], answer: 0 },
  { q: '"Open-weight" models are ones whose…', choices: ['Parameters anyone can download', 'Training data is public', 'Answers are always correct', 'Weights change daily'], answer: 0 },
  { q: 'A healthy pattern for using AI in analysis is…', choices: ['Paste in data you do not understand and ship the output', 'You frame the question and check the result; the model speeds up the middle', 'Let the model choose the data source', 'Never verify numbers'], answer: 1 },
];
