export default [
  { q: 'At 3% inflation, $100 buys roughly what…', choices: ['$103 bought last year', '$97 bought last year', '$100 bought last year', '$130 bought last year'], answer: 1 },
  { q: '"Core" inflation strips out…', choices: ['Housing', 'Food and energy', 'Services', 'Imports'], answer: 1 },
  { q: 'Inflation tends to help…', choices: ['Savers holding cash', 'People on fixed incomes', 'Borrowers with fixed-rate debt', 'Nobody'], answer: 2 },
  { q: 'Inflation is 4% and your savings pay 1.5%. Your buying power…', choices: ['Grows 1.5% a year', 'Falls about 2.5% a year', 'Stays the same', 'Grows 4%'], answer: 1 },
  { q: 'Using the rule of 72, money at 6% doubles in about…', choices: ['6 years', '12 years', '24 years', '72 years'], answer: 1 },
  { q: 'A $300,000 30-year mortgage at 7% instead of 3% costs roughly…', choices: ['$75 more a month', '$750 more a month', '$7,500 more a month', 'The same'], answer: 1 },
  { q: 'The popular shorthand for a recession is…', choices: ['One bad month', 'Two consecutive quarters of shrinking GDP', 'A stock market drop of 10%', 'Rising prices'], answer: 1 },
  { q: 'GDP grows 2% while population grows 3%. The average person is…', choices: ['Better off', 'Worse off, by about 1%', 'Unchanged', 'Impossible to say'], answer: 1 },
  { q: 'Unemployment usually…', choices: ['Falls as soon as a recession begins', 'Rises months after output falls and stays high after growth resumes', 'Is unrelated to recessions', 'Peaks before the recession'], answer: 1 },
  { q: 'Moving into a higher US tax bracket means…', choices: ['All your income is taxed at the higher rate', 'Only the income above the threshold is taxed at the higher rate', 'You take home less', 'You must file twice'], answer: 1 },
  { q: 'Your "effective" tax rate is…', choices: ['Always higher than your marginal rate', 'Total tax divided by income, always lower than the marginal rate', 'The rate on your last dollar', 'The sales tax'], answer: 1 },
  { q: 'A tax credit…', choices: ['Reduces taxable income', 'Reduces the tax itself, dollar for dollar', 'Increases your refund only if you itemize', 'Is a loan'], answer: 1 },
  { q: 'A Brooklyn paycheck shows three income-tax lines because…', choices: ['Of a payroll error', 'Federal, New York State, and New York City each levy income tax', 'Brooklyn is a separate state', 'Of Social Security'], answer: 1 },
  { q: 'Egg prices doubled in 2022–23 mainly because…', choices: ['A conspiracy', 'Avian flu cut supply while demand stayed', 'A new tax', 'People ate more eggs'], answer: 1 },
  { q: 'A strict rent cap tends over time to…', choices: ['Increase the number of apartments', 'Reduce available apartments and create queues', 'Lower demand', 'Have no effect'], answer: 1 },
  { q: 'Petrol prices swing a lot on small supply shocks because…', choices: ['Demand barely changes when prices rise', 'Petrol is cheap', 'There are many substitutes', 'Of taxes'], answer: 0 },
  { q: 'Deposit insurance makes banks safer because…', choices: ['Banks lend less', 'It removes the incentive to run, so panics do not start', 'It raises interest rates', 'It is paid out often'], answer: 1 },
  { q: 'Silicon Valley Bank failed in 2023 partly because…', choices: ['It held no bonds', 'Its long-term bonds lost value when rates rose and uninsured depositors ran', 'It was too small', 'Of a cyberattack'], answer: 1 },
  { q: 'A tariff is paid by…', choices: ['The foreign government', 'The importer, and mostly passed to domestic buyers', 'The exporter\'s workers', 'Nobody'], answer: 1 },
  { q: 'If you earn dollars and send money to France, a strong dollar is…', choices: ['Bad news', 'Good news: each dollar buys more euros', 'Irrelevant', 'Only good in summer'], answer: 1 },
];
