export default [
  { q: 'Around what year did Gutenberg\'s printing system appear?', choices: ['1250', '1450', '1650', '1750'], answer: 1 },
  { q: 'Printers favored local languages over Latin mainly because…', choices: ['Latin type was expensive', 'Local languages reached far more buyers', 'The Church required it', 'Latin had no alphabet'], answer: 1 },
  { q: 'Which movement spread quickly thanks to the press, starting in 1517?', choices: ['The Renaissance', 'The Reformation', 'The Enlightenment', 'The Crusades'], answer: 1 },
  { q: 'What did the Third Estate represent in 1789?', choices: ['The clergy', 'The nobility', 'Everyone else, about 97% of the population', 'The army'], answer: 2 },
  { q: 'The political terms "left" and "right" come from…', choices: ['Roman senate traditions', 'Seating in the 1789 National Assembly', 'British parliament benches', 'Napoleon\'s army'], answer: 1 },
  { q: 'Which is a lasting legacy of the French Revolution?', choices: ['The metric system', 'The gold standard', 'The Gregorian calendar', 'The steam engine'], answer: 0 },
  { q: 'Where did the Industrial Revolution begin?', choices: ['France', 'Germany', 'Britain', 'The United States'], answer: 2 },
  { q: 'Why did the steam engine matter more than a better water wheel?', choices: ['It was cheaper to build', 'It let factories run anywhere coal could be delivered, not just beside rivers', 'It needed no fuel', 'It was quieter'], answer: 1 },
  { q: 'The First World War was triggered by the assassination of…', choices: ['Tsar Nicholas II', 'Archduke Franz Ferdinand', 'Kaiser Wilhelm II', 'President Poincaré'], answer: 1 },
  { q: 'Which empire did NOT collapse as a result of the First World War?', choices: ['Ottoman', 'Austro-Hungarian', 'British', 'Russian'], answer: 2 },
  { q: 'France\'s military deaths in the First World War were roughly…', choices: ['140,000', '1.4 million', '4 million', '14 million'], answer: 1 },
  { q: 'In the Great Depression, why did falling prices make things worse?', choices: ['People bought too much', 'Debts stayed fixed while incomes fell, and people delayed spending', 'Exports boomed', 'Banks lent more'], answer: 1 },
  { q: 'US deposit insurance was created in…', choices: ['1913', '1929', '1933', '1945'], answer: 2 },
  { q: 'Which economist argued governments should spend when private demand collapses?', choices: ['Adam Smith', 'John Maynard Keynes', 'Milton Friedman', 'Karl Marx'], answer: 1 },
  { q: 'The Second World War in Europe began with Germany\'s invasion of…', choices: ['France', 'Poland', 'Czechoslovakia', 'Belgium'], answer: 1 },
  { q: 'Which institution was founded in 1945 in the aftermath of the war?', choices: ['The League of Nations', 'The United Nations', 'The European Union', 'The World Trade Organization'], answer: 1 },
  { q: 'The European project began in 1951 by pooling which industries?', choices: ['Banking and insurance', 'Coal and steel', 'Wine and cheese', 'Railways and ports'], answer: 1 },
  { q: 'The Berlin Wall was built in…', choices: ['1945', '1953', '1961', '1975'], answer: 2 },
  { q: 'Which 1989 event made the wall harder to maintain?', choices: ['Hungary opened its border with Austria', 'The US invaded East Germany', 'France left NATO', 'The euro was introduced'], answer: 0 },
  { q: 'The Soviet Union dissolved in…', choices: ['1989', '1990', 'December 1991', '1995'], answer: 2 },
];
